### ISSUE TITLE
Something wrong when i use DeployInstantiateChaincode

### ISSUE THREAD

**Issue by githubofljl** [IBM/blockchain-application-using-fabric-java-sdk#37]
When I run DeployInstantiateChaincode for the first time,i met this and i dont know why
`16:47:27.894 [main] ERROR org.hyperledger.fabric.sdk.Channel - Channel Channel{id: 1, name: mychannel} sending proposal with transaction 858e3874edde327995944626218586baddb8100d9bafc1b1603e2e73a8887d2c to Peer{ id: 3, name: peer0.org1.example.com, channelName: mychannel, url: grpc://0.0.0.0:7051} failed because of timeout(10000 milliseconds) expiration
java.util.concurrent.TimeoutException: Waited 10000 milliseconds for io.grpc.stub.ClientCalls$GrpcFuture@7d446ed1[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=protos.Endorser/ProcessProposal, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@d771cc9, responseMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@36b4091c, schemaDescriptor=org.hyperledger.fabric.protos.peer.EndorserGrpc$EndorserMethodDescriptorSupplier@4671115f}}}}}]]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:471)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4108)
	at org.hyperledger.fabric.sdk.Channel.sendInstantiationProposal(Channel.java:2520)
	at org.hyperledger.fabric.sdk.Channel.sendInstantiationProposal(Channel.java:2480)
	at org.app.client.ChannelClient.instantiateChainCode(ChannelClient.java:198)
	at org.app.network.DeployInstantiateChaincode.main(DeployInstantiateChaincode.java:124)
Sept 05, 2019 4:47:28  PM org.app.client.ChannelClient instantiateChainCode
INFO: Chaincode mycc_test on channel mychannel instantiation java.util.concurrent.CompletableFuture@65b104b9[Completed exceptionally]
Sept 05, 2019 4:47:28 PM org.app.network.DeployInstantiateChaincode main
INFO: mycc_test- Chain code instantiation FAILURE
Sept 05, 2019 4:47:28 PM org.app.network.DeployInstantiateChaincode main
INFO: mycc_test- Chain code instantiation FAILURE
Sept 05, 2019 4:47:28 PM org.app.network.DeployInstantiateChaincode main
INFO: mycc_test- Chain code instantiation FAILURE
Sept 05, 2019 4:47:28 PM org.app.network.DeployInstantiateChaincode main
INFO: mycc_test- Chain code instantiation FAILURE
`
but when i try to run twice or more it can work.

**Comment by balajikadambi** [comment]
@liujianglin1 It appears to be a timeout issue. The proposal wait time has been set to 180000ms in the instantiateChainCode method of ChannelClient.java file. Please increase it a bit and see if it helps.

**Comment by liujianglin1** [comment]
> @ liujianglin1这似乎是一个超时问题。在ChannelClient.java文件的instantiateChainCode方法中，提议等待时间已设置为180000ms。请稍微加一点，看看是否有帮助。

i tried this ,but it seems no help.

**Comment by longtranvnext** [comment]
@balajikadambi , how i can deploy java chaincode not use go ?

**Comment by liujianglin1** [comment]
> @balajikadambi , how i can deploy java chaincode not use go ?

change the CHAINCODE_1_PATH and CHAINCODE_ROOT_DIR in file Config.java

**Comment by longtranvnext** [comment]
@liujianglin1 

1. build source code java fabcar then copy jar to blockchain-application-using-fabric-java-sdk/network_resources/chaincode/src/chaincode/chaincode.jar

/usr/lib/jvm/jdk1.8.0_131/bin/java -javaagent:/home/longtran/working/workspace/tools/ideaIU-2018.3.1-no-jdk/idea-IU-183.4588.61/lib/idea_rt.jar=37673:/home/longtran/working/workspace/tools/ideaIU-2018.3.1-no-jdk/idea-IU-183.4588.61/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/jdk1.8.0_131/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/jaccess.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_131/jre/lib/rt.jar:/home/longtran/working/workspace/sotanext/blockchain-application-using-fabric-java-sdk/java/out/production/main:/home/longtran/working/workspace/sotanext/blockchain-application-using-fabric-java-sdk/java/target/blockchain-client.jar:/home/longtran/working/workspace/sotanext/blockchain-application-using-fabric-java-sdk/java/target/blockchain-java-sdk-0.0.1-SNAPSHOT.jar:/home/longtran/working/workspace/sotanext/blockchain-application-using-fabric-java-sdk/java/target/blockchain-java-sdk-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.example.network.DeployInstantiateChaincode
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sep 16, 2019 5:00:58 PM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org1MSP admin
Sep 16, 2019 5:01:01 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment SUCCESS
Sep 16, 2019 5:01:01 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment SUCCESS
Sep 16, 2019 5:01:01 PM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org2MSP admin
Sep 16, 2019 5:01:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment SUCCESS
Sep 16, 2019 5:01:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment SUCCESS
Sep 16, 2019 5:01:04 PM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiate proposal request fabcar on channel mychannel with Fabric client Org2MSP admin
Sep 16, 2019 5:01:04 PM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiating Chaincode ID fabcar on channel mychannel
Sep 16, 2019 5:13:04 PM org.example.client.ChannelClient instantiateChainCode
INFO: Chaincode fabcar on channel mychannel instantiation java.util.concurrent.CompletableFuture@766653e6[Completed exceptionally]
Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE

Process finished with exit code 0

**Comment by balajikadambi** [comment]
@longtranvnext we have not tested with Java chaincode. can you login to docker container shell of the peers and orderer to see if there are any errors.

**Comment by solartes** [comment]
Any solution? It happens the same to me. Sometimes works sometimes does not work

**Comment by balajikadambi** [comment]
@solartes we did not encounter the issue when we tried. so, not sure whats causing it. I would recommend debugging by logging into the docker container shell for the peers and orderer.

**Comment by longtran84** [comment]
@balajikadambi do you have a demo code about hyperledger java chaincode?

**Comment by balajikadambi** [comment]
@longtran84 It is the same as the code shared on this GitHub repo.

**Comment by longtran84** [comment]
your code use GO, i wanna use hyperledger java chaincode?

**Comment by maheshwarishikha** [comment]
@longtran84 , Sorry, this repo is not tested using Java chaincode. So not sure about the steps too. Debugging as per the error messages in logs might help.

**Comment by magicmae** [comment]
> @liujianglin1
> 
> 1. build source code java fabcar then copy jar to blockchain-application-using-fabric-java-sdk/network_resources/chaincode/src/chaincode/chaincode.jar
> 
> log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> Sep 16, 2019 5:00:58 PM org.example.client.FabricClient deployChainCode
> INFO: Deploying chaincode fabcar using Fabric client Org1MSP admin
> Sep 16, 2019 5:01:01 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code deployment SUCCESS
> Sep 16, 2019 5:01:01 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code deployment SUCCESS
> Sep 16, 2019 5:01:01 PM org.example.client.FabricClient deployChainCode
> INFO: Deploying chaincode fabcar using Fabric client Org2MSP admin
> Sep 16, 2019 5:01:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code deployment SUCCESS
> Sep 16, 2019 5:01:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code deployment SUCCESS
> Sep 16, 2019 5:01:04 PM org.example.client.ChannelClient instantiateChainCode
> INFO: Instantiate proposal request fabcar on channel mychannel with Fabric client Org2MSP admin
> Sep 16, 2019 5:01:04 PM org.example.client.ChannelClient instantiateChainCode
> INFO: Instantiating Chaincode ID fabcar on channel mychannel
> Sep 16, 2019 5:13:04 PM org.example.client.ChannelClient instantiateChainCode
> INFO: Chaincode fabcar on channel mychannel instantiation java.util.concurrent.CompletableFuture@766653e6[Completed exceptionally]
> Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code instantiation FAILURE
> Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code instantiation FAILURE
> Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code instantiation FAILURE
> Sep 16, 2019 5:13:04 PM org.example.network.DeployInstantiateChaincode main
> INFO: fabcar- Chain code instantiation FAILURE
> 
> Process finished with exit code 0

I modified 1.4.1 to x86_64-1.0.0  of fabric edition in docker-compose.yml. Then it works.

**Comment by longtran84** [comment]
@magicmae can you help me update to Hyperledger Fabric 2 network ?

**Comment by longtran84** [comment]
@balajikadambi can you help me update to Hyperledger Fabric 2 network ?

**Comment by bigdaronlee163** [comment]
i  met this problem too，follow the solution  by  @balajikadambi  to  increase The proposal wait time to  280000 ， 380000 and  turn out that  this Method doesnot work at  all 。please help！!!

daronlee@daronlee-virtual-machine:~/learning/experiment/tutorial/blockchain-application-using-fabric-java-sdk/network_resources$ java -cp blockchain-client.jar org.example.network.DeployInstantiateChaincode
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Aug 04, 2020 8:34:02 PM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org1MSP admin
Aug 04, 2020 8:34:02 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 04, 2020 8:34:02 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 04, 2020 8:34:02 PM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org2MSP admin
Aug 04, 2020 8:34:02 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 04, 2020 8:34:02 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 04, 2020 8:34:02 PM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiate proposal request fabcar on channel mychannel with Fabric client Org2MSP admin
Aug 04, 2020 8:34:02 PM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiating Chaincode ID fabcar on channel mychannel
Aug 04, 2020 8:34:06 PM org.example.client.ChannelClient instantiateChainCode
INFO: Chaincode fabcar on channel mychannel instantiation java.util.concurrent.CompletableFuture@50313382[Completed exceptionally]
Aug 04, 2020 8:34:06 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 04, 2020 8:34:06 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 04, 2020 8:34:06 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 04, 2020 8:34:06 PM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE

**Comment by bigdaronlee163** [comment]
same  problem....

daronlee@daronlee-virtual-machine:~/learning/experiment/tutorial/blockchain-application-using-fabric-java-sdk/network_resources$ java -cp blockchain-client.jar org.example.network.DeployInstantiateChaincode
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Aug 05, 2020 11:16:05 AM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org1MSP admin
Aug 05, 2020 11:16:05 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 05, 2020 11:16:05 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 05, 2020 11:16:05 AM org.example.client.FabricClient deployChainCode
INFO: Deploying chaincode fabcar using Fabric client Org2MSP admin
Aug 05, 2020 11:16:05 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 05, 2020 11:16:05 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code deployment FAILURE
Aug 05, 2020 11:16:05 AM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiate proposal request fabcar on channel mychannel with Fabric client Org2MSP admin
Aug 05, 2020 11:16:05 AM org.example.client.ChannelClient instantiateChainCode
INFO: Instantiating Chaincode ID fabcar on channel mychannel
Aug 05, 2020 11:16:11 AM org.example.client.ChannelClient instantiateChainCode
INFO: Chaincode fabcar on channel mychannel instantiation java.util.concurrent.CompletableFuture@1cb346ea[Completed exceptionally]
Aug 05, 2020 11:16:11 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 05, 2020 11:16:11 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 05, 2020 11:16:11 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Aug 05, 2020 11:16:11 AM org.example.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
daronlee@daronlee-virtual-machine:~/learning/experiment/tutorial/blockchain-application-using-fabric-java-sdk/network_resources$

**Comment by bala-v09** [comment]
Hi all, I was able to resolve this issue by changing the version of the docker image from 1.4.1 to 1.4 in docker-compose.yml. If you check the docker logs of the peer you can see that it fails because it is trying to pull a peer dependency but gets a 404 as the latest tag is no longer supported. I was able to get it working, and my docker-compose.y😂ml looks like this:
```
version: '2'

networks:
  custom:

services:

  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/26447f667024067fc5efbd2605f92b410dc2d0ce10408890949eb71ac7fbe2f9_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network_resources/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg1
    networks:
      - custom

  ca.org2.example.com:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/384b0c0e6faf5d2c256f1265a89aecde606e7577869e07f3e1b17ad318607413_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network_resources/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg2
    networks:
      - custom

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:1.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    networks:
      - custom
    ports:
      - 7050:7050
    volumes:
        - ../network_resources/config/:/etc/hyperledger/configtx
        - ../network_resources/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/msp/peerOrg2

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - custom
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
```
